name: forceapp
description: FORCE DELIVERY
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.2.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.17.0
  supabase_flutter: ^2.5.0
  google_fonts: ^6.1.0
  pdf: ^3.10.7
  app_links: 6.2.1

  printing: ^5.11.1
  geolocator: 10.1.1
  image_picker: ^1.0.4
  fl_chart: ^0.68.0
  intl: ^0.19.0
  permission_handler: 11.3.1
flutter:
  uses-material-design: true


